version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.1
    - 1.8.1
    - 1.9.1
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.1
    - 1.89.0
    - 1.92.0
    - 1.93.0
  - dependency-name: oj
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.1
  - dependency-name: rack-attack
    versions:
    - 6.4.0
  - dependency-name: derailed_benchmarks
    versions:
    - 2.0.0
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: brakeman
    versions:
    - 4.10.0
  - dependency-name: sanitize
    versions:
    - 5.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: intl-messageformat
    versions:
    - 9.4.4
    - 9.4.6
    - 9.4.7
    - 9.5.2
    - 9.5.3
    - 9.6.3
    - 9.6.6
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.12.15
    - 7.12.17
    - 7.13.10
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.12
    - 7.13.9
  - dependency-name: sass
    versions:
    - 1.32.4
    - 1.32.5
    - 1.32.6
    - 1.32.8
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: react-toggle
    versions:
    - 4.1.1
